# Site settings
title: Eric Quanz - Designer turned front-end developer
email: eric.quanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Front-end developer and UI / graphic designer
    based in Porto Alegre, Brazil. Eric Quanz has over 4 years experience
    in responsive website development and design.
url: "http://ericquanz.com" # the base hostname & protocol for your site
twitter_username: ericorruption
github_username:  ericorruption

# Build settings
sass:
    style: :compressed
gems:
    - jekyll-sitemap