exclude: [node_modules]

# Site settings
title: Eric Quanz - Designer turned front-end developer
email: eric.quanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Front-end developer and designer
    based in Porto Alegre, Brazil. Eric Quanz has over 5 years experience
    in responsive website development and design.
url: "https://ericquanz.com" # the base hostname & protocol for your site
twitter_username: ericorruption
github_username:  ericorruption

# Build settings
sass:
    style: :compressed
gems:
    - jekyll-sitemap

# Front Matter defaults
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            categories: "blog"
    -
        scope:
            path: "projects"
            type: "pages"
        values:
            layout: "page"
