exclude:
  - node_modules
  - README.md
  - package.json
  - vendor

# Site settings
title: Eric Quanz - Front-End Developer / Engineer
email: eric.quanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-End developer / engineer with a design background. Over 10 years experience
  developing and designing websites and web application. Bridging the gap between development and design.
url: "https://ericquanz.com" # the base hostname & protocol for your site
twitter_username: ericorruption
github_username: ericorruption

# Build settings
sass:
  style: :compressed
plugins:
  - jekyll-sitemap

repository: ericorruption/ericorruption.github.io

# Outputting
permalink: pretty

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "page"
